package com.example.weappdemo02.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.image
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.secondname
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private String secondname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.temperature
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sweetness
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private String sweetness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.material
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withPid(Integer pid) {
        this.setPid(pid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withType(String type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.image
     *
     * @return the value of product.image
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withImage(String image) {
        this.setImage(image);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.image
     *
     * @param image the value for product.image
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withPrice(BigDecimal price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withStock(Integer stock) {
        this.setStock(stock);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.secondname
     *
     * @return the value of product.secondname
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public String getSecondname() {
        return secondname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withSecondname(String secondname) {
        this.setSecondname(secondname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.secondname
     *
     * @param secondname the value for product.secondname
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setSecondname(String secondname) {
        this.secondname = secondname == null ? null : secondname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.temperature
     *
     * @return the value of product.temperature
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withTemperature(String temperature) {
        this.setTemperature(temperature);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.temperature
     *
     * @param temperature the value for product.temperature
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sweetness
     *
     * @return the value of product.sweetness
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public String getSweetness() {
        return sweetness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withSweetness(String sweetness) {
        this.setSweetness(sweetness);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sweetness
     *
     * @param sweetness the value for product.sweetness
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setSweetness(String sweetness) {
        this.sweetness = sweetness == null ? null : sweetness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.material
     *
     * @return the value of product.material
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public Product withMaterial(String material) {
        this.setMaterial(material);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.material
     *
     * @param material the value for product.material
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Aug 16 13:20:10 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", image=").append(image);
        sb.append(", price=").append(price);
        sb.append(", stock=").append(stock);
        sb.append(", secondname=").append(secondname);
        sb.append(", temperature=").append(temperature);
        sb.append(", sweetness=").append(sweetness);
        sb.append(", material=").append(material);
        sb.append("]");
        return sb.toString();
    }
}